{% set version = "0.17.34" %}

package:
  name: ruamel_yaml
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/r/ruamel.yaml/ruamel.yaml-{{ version }}.tar.gz
  sha256: 6ffd0a1906ddeac4a46b7b53d288a5a26bfab8f1986ddab3d8e406beda7e6e72

build:
  number: 0
  no_link: .*\.(pyd|dll)  # [win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ compiler("c") }}
    - posix                # [win]

  host:
    - python
    - pip
    - cython
    - yaml

  run:
    - python
    - yaml

test:
  requires:
    - pip
  imports:
    - ruamel_yaml
    - ruamel_yaml.ext._ruamel_yaml
  commands:
    # check that ruamel_yaml doesn't claim to be ruamel.yaml
    - if pip show ruamel.yaml; then exit 1; fi  # [unix]
    - $PYTHON -m pip install ruamel.yaml  # [unix]
    - $PYTHON -c "import ruamel.yaml"  # [unix]
    - pip check

about:
  home: https://sourceforge.net/p/ruamel-yaml/code/ci/default/tree
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A patched copy of ruamel.yaml.

extra:
  recipe-maintainers:
    - jakirkham
    - mbargull
    - isuruf
