{% set version = "0.15.74" %}
# The version_info tuple in __init__.py must also be updated

package:
  name: ruamel_yaml
  version: {{ version }}

source:
  url: https://bitbucket.org/ruamel/yaml/get/{{ version }}.tar.gz
  sha256: f919af95d23c9a8353a81e45d8b4150c245da4d5975950390003405706bbd338
  patches:
    - ordereddict_test.patch

build:
  number: 1000
  no_link: .*\.(pyd|dll)   # [win]

requirements:
  build:
    - {{ compiler("c") }}
    - posix                # [win]

  host:
    - python
    - pip
    - cython
    - yaml

  run:
    - python
    - yaml

test:
  requires:
    - pytest
    - conda

  imports:
    - ruamel_yaml
    - ruamel_yaml.ext._ruamel_yaml

about:
  home: https://bitbucket.org/ruamel/yaml
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A patched copy of ruamel.yaml.

extra:
  recipe-maintainers:
    - jakirkham
    - mbargull
