{% set version = "0.11.14" %}

package:
  name: ruamel_yaml
  version: {{ version }}

source:
  fn: ruamel_yaml-{{ version }}.tar.gz
  url: https://bitbucket.org/ruamel/yaml/get/{{ version }}.tar.gz
  sha256: b78d394e192b6d0911bd59f794ceea88143fac4e373b76ed7e48143a2a29b33c

build:
  number: 1
  no_link: .*\.(pyd|dll)  # [win]
  features:
    - vc9  # [win and py27]
    - vc10  # [win and py34]
    - vc14  # [win and (py35 or py36)]

requirements:
  build:
    - toolchain
    - posix               # [win]
    - python
    - setuptools
    - cython
    - yaml

  run:
    - python
    - yaml

test:
  requires:
    - pytest

  imports:
    - ruamel_yaml
    - ruamel_yaml.ext._ruamel_yaml

about:
  home: https://bitbucket.org/ruamel/yaml
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A patched copy of ruamel.yaml.

extra:
  recipe-maintainers:
    - jakirkham
