{% set version = "0.15.44" %}
# The version_info tuple in __init__.py must also be updated

package:
  name: ruamel_yaml
  version: {{ version }}

source:
  url: https://bitbucket.org/ruamel/yaml/get/{{ version }}.tar.gz
  sha256: 51d9435dfccf55e679456181869019221daf409b1e74640d5dfa97d5976f823b
  patches:
    - ordereddict_test.patch

build:
  number: 1
  no_link: .*\.(pyd|dll)   # [win]

requirements:
  build:
    - posix                # [win]
    - {{ compiler('c') }}
  host:
    - {{ compiler("c") }}

  host:
    - python
    - pip
    - cython
    - yaml

  run:
    - python
    - yaml

test:
  requires:
    - pytest

  imports:
    - ruamel_yaml
    - ruamel_yaml.ext._ruamel_yaml

about:
  home: https://bitbucket.org/ruamel/yaml
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A patched copy of ruamel.yaml.

extra:
  recipe-maintainers:
    - jakirkham
    - mbargull
