{% set version = "0.15.80" %}

package:
  name: ruamel_yaml
  version: {{ version }}

source:
  url: https://bitbucket.org/ruamel/yaml/get/{{ version }}.tar.gz
  sha256: 8529f909d8983a2b80bb3af60e425c418edf54f2fa132d863c43b3353f901203
  patches:
    - ordereddict_test.patch

build:
  number: 1001
  no_link: .*\.(pyd|dll)   # [win]

requirements:
  build:
    - {{ compiler("c") }}
    - posix                # [win]

  host:
    - python
    - pip
    - cython

  run:
    - python

test:
  requires:
    - pytest

  imports:
    - ruamel_yaml
    - ruamel_yaml.ext._ruamel_yaml

about:
  home: https://bitbucket.org/ruamel/yaml
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A patched copy of ruamel.yaml.

extra:
  recipe-maintainers:
    - jakirkham
    - mbargull
